// operationsActivityService.js — Mock data for OperationsHub tabs
// Activity log, court reservations, F&B orders, and auto check-in schema.

export const COURT_TYPES = ['Tennis', 'Pickleball'];

export const AUTO_CHECKIN_SCHEMA = {
  memberId: 'string',
  memberName: 'string',
  clubId: 'string',
  lat: 'number',
  lng: 'number',
  timestamp: 'ISO string',
  teetime: 'ISO string or null',
  autoCheckedIn: 'boolean',
  notifiedAt: 'ISO string or null',
};

export function getActivityLog() {
  return [
    {
      id: 'act_001',
      type: 'agent_action',
      memberName: 'James Whitfield',
      memberId: 'mbr_t01',
      description: 'Retention outreach sent: tee time offer for Saturday 7 AM',
      agentId: 'agent_retention',
      agentLabel: 'Retention Agent',
      timestamp: '2026-04-16T08:14:00Z',
      status: 'approved',
      notes: 'Member had not booked in 21 days. Offer accepted within 4 minutes.',
      result: 'Tee time booked for Saturday 7:00 AM.',
    },
    {
      id: 'act_002',
      type: 'member_alert',
      memberName: 'Anne Jordan',
      memberId: 'mbr_t04',
      description: 'At-risk flag raised: visit frequency dropped below threshold',
      agentId: 'agent_health',
      agentLabel: 'Member Health Agent',
      timestamp: '2026-04-16T07:52:00Z',
      status: 'pending',
      notes: 'Last visit was 34 days ago. Previous pattern was weekly.',
      result: null,
    },
    {
      id: 'act_003',
      type: 'concierge',
      memberName: 'Robert Callahan',
      memberId: 'mbr_t05',
      description: 'Concierge chat: requested private dining reservation for Saturday evening',
      agentId: null,
      agentLabel: 'Concierge',
      timestamp: '2026-04-16T07:41:00Z',
      status: 'completed',
      notes: 'Party of 6, 7:30 PM. Special request for gluten-free menu.',
      result: 'Reservation confirmed. Kitchen notified.',
    },
    {
      id: 'act_004',
      type: 'fb_order',
      memberName: 'Sandra Chen',
      memberId: 'mbr_t06',
      description: 'F&B pickup order placed: Club Sandwich, Arnold Palmer, side of fries',
      agentId: null,
      agentLabel: 'F&B POS',
      timestamp: '2026-04-16T12:03:00Z',
      status: 'completed',
      notes: 'Pickup at 12:30 PM. Member arrived on time.',
      result: 'Order picked up.',
    },
    {
      id: 'act_005',
      type: 'court_booking',
      memberName: 'David Miller',
      memberId: 'mbr_d01',
      description: 'Pickleball court reserved: Court 2, Thursday 6:00 PM, 90 min',
      agentId: null,
      agentLabel: 'Scheduling',
      timestamp: '2026-04-15T16:30:00Z',
      status: 'approved',
      notes: 'Party of 4. Member requested ball machine setup.',
      result: 'Reservation confirmed.',
    },
    {
      id: 'act_006',
      type: 'agent_action',
      memberName: 'Linda Leonard',
      memberId: 'mbr_t07',
      description: 'Win-back message sent: personalized offer for complimentary lesson',
      agentId: 'agent_retention',
      agentLabel: 'Retention Agent',
      timestamp: '2026-04-15T14:20:00Z',
      status: 'dismissed',
      notes: 'Member flagged as ghost. Agent confidence 72%. Staff dismissed.',
      result: null,
    },
    {
      id: 'act_007',
      type: 'checkin',
      memberName: 'Susan Park',
      memberId: 'mbr_d02',
      description: 'Auto check-in detected: member arrived at parking lot gate',
      agentId: 'agent_checkin',
      agentLabel: 'Check-in Agent',
      timestamp: '2026-04-15T09:07:00Z',
      status: 'completed',
      notes: 'GPS within 50m of main entrance. Tee time at 9:30 AM matched.',
      result: 'Member checked in. Locker and cart assigned.',
    },
    {
      id: 'act_008',
      type: 'member_alert',
      memberName: 'Tom Bradford',
      memberId: 'mbr_d03',
      description: 'Complaint received: slow service at the 19th hole bar',
      agentId: 'agent_service',
      agentLabel: 'Service Agent',
      timestamp: '2026-04-15T18:45:00Z',
      status: 'pending',
      notes: 'Member reported 20-minute wait for post-round drinks.',
      result: null,
    },
    {
      id: 'act_009',
      type: 'concierge',
      memberName: 'James Whitfield',
      memberId: 'mbr_t01',
      description: 'Concierge chat: asked about wine dinner guest list availability',
      agentId: null,
      agentLabel: 'Concierge',
      timestamp: '2026-04-14T19:11:00Z',
      status: 'completed',
      notes: 'Confirmed 2 spots available. Member added wife to list.',
      result: 'Guest registration confirmed.',
    },
    {
      id: 'act_010',
      type: 'agent_action',
      memberName: 'Anne Jordan',
      memberId: 'mbr_t04',
      description: 'Re-engagement email queued: summer social calendar preview',
      agentId: 'agent_engagement',
      agentLabel: 'Engagement Agent',
      timestamp: '2026-04-14T10:00:00Z',
      status: 'approved',
      notes: 'Segment: lapsed social members. Email scheduled for 10 AM.',
      result: 'Email delivered. Open rate tracked.',
    },
    {
      id: 'act_011',
      type: 'fb_order',
      memberName: 'Robert Callahan',
      memberId: 'mbr_t05',
      description: 'F&B pickup order placed: Caesar Salad, sparkling water, brownie',
      agentId: null,
      agentLabel: 'F&B POS',
      timestamp: '2026-04-14T11:47:00Z',
      status: 'completed',
      notes: 'Pickup at noon.',
      result: 'Order picked up.',
    },
    {
      id: 'act_012',
      type: 'court_booking',
      memberName: 'Linda Leonard',
      memberId: 'mbr_t07',
      description: 'Tennis court reserved: Court 1, Friday 8:00 AM, 60 min',
      agentId: null,
      agentLabel: 'Scheduling',
      timestamp: '2026-04-13T17:00:00Z',
      status: 'approved',
      notes: 'Singles match. Pro lesson requested for first 30 minutes.',
      result: 'Reservation confirmed. Pro availability verified.',
    },
    {
      id: 'act_013',
      type: 'checkin',
      memberName: 'David Miller',
      memberId: 'mbr_d01',
      description: 'Auto check-in detected: member arrived via rear entrance',
      agentId: 'agent_checkin',
      agentLabel: 'Check-in Agent',
      timestamp: '2026-04-13T07:55:00Z',
      status: 'completed',
      notes: 'GPS matched within 30m. No tee time on file, walk-in flagged.',
      result: 'Walk-in added to standby list.',
    },
    {
      id: 'act_014',
      type: 'member_alert',
      memberName: 'Sandra Chen',
      memberId: 'mbr_t06',
      description: 'Membership renewal notice: dues payment 5 days overdue',
      agentId: 'agent_billing',
      agentLabel: 'Billing Agent',
      timestamp: '2026-04-12T08:00:00Z',
      status: 'pending',
      notes: 'First notice sent. No response yet.',
      result: null,
    },
    {
      id: 'act_015',
      type: 'agent_action',
      memberName: 'Tom Bradford',
      memberId: 'mbr_d03',
      description: 'Service recovery offer sent: complimentary round for slow-round experience',
      agentId: 'agent_service',
      agentLabel: 'Service Agent',
      timestamp: '2026-04-12T09:30:00Z',
      status: 'approved',
      notes: 'Member score dropped after slow round on 11th. Recovery offer issued.',
      result: 'Member replied positively. Round scheduled.',
    },
    {
      id: 'act_016',
      type: 'concierge',
      memberName: 'Susan Park',
      memberId: 'mbr_d02',
      description: 'Concierge chat: equipment rental inquiry for guest',
      agentId: null,
      agentLabel: 'Concierge',
      timestamp: '2026-04-11T15:22:00Z',
      status: 'completed',
      notes: 'Guest requires full set rental for Sunday.',
      result: 'Rental reserved. Guest name added to booking.',
    },
    {
      id: 'act_017',
      type: 'fb_order',
      memberName: 'Susan Park',
      memberId: 'mbr_d02',
      description: 'F&B pickup order placed: Grilled salmon, house salad, iced tea',
      agentId: null,
      agentLabel: 'F&B POS',
      timestamp: '2026-04-11T13:05:00Z',
      status: 'completed',
      notes: 'Pickup at 1:30 PM. Allergy flag: shellfish.',
      result: 'Order picked up.',
    },
    {
      id: 'act_018',
      type: 'agent_action',
      memberName: 'Linda Leonard',
      memberId: 'mbr_t07',
      description: 'Ghost member report generated and shared with GM',
      agentId: 'agent_health',
      agentLabel: 'Member Health Agent',
      timestamp: '2026-04-10T08:45:00Z',
      status: 'completed',
      notes: 'Zero visits in 63 days. Report included last 5 interactions.',
      result: 'GM reviewed and scheduled personal call.',
    },
    {
      id: 'act_019',
      type: 'court_booking',
      memberName: 'Tom Bradford',
      memberId: 'mbr_d03',
      description: 'Pickleball court reserved: Court 3, Sunday 10:00 AM, 60 min',
      agentId: null,
      agentLabel: 'Scheduling',
      timestamp: '2026-04-10T11:00:00Z',
      status: 'approved',
      notes: 'Doubles match. Party of 4.',
      result: 'Reservation confirmed.',
    },
    {
      id: 'act_020',
      type: 'member_alert',
      memberName: 'Robert Callahan',
      memberId: 'mbr_t05',
      description: 'Declining member flag: round frequency down 60% over 90 days',
      agentId: 'agent_health',
      agentLabel: 'Member Health Agent',
      timestamp: '2026-04-09T08:10:00Z',
      status: 'pending',
      notes: 'Corporate member, 4 guests last year. High churn risk.',
      result: null,
    },
  ];
}

export function getCourtReservations() {
  return [
    {
      id: 'court_001',
      memberName: 'James Whitfield',
      memberId: 'mbr_t01',
      courtType: 'Tennis',
      date: '2026-04-17',
      time: '07:00',
      duration: 60,
      partySize: 2,
      status: 'confirmed',
    },
    {
      id: 'court_002',
      memberName: 'David Miller',
      memberId: 'mbr_d01',
      courtType: 'Pickleball',
      date: '2026-04-17',
      time: '09:30',
      duration: 90,
      partySize: 4,
      status: 'confirmed',
    },
    {
      id: 'court_003',
      memberName: 'Linda Leonard',
      memberId: 'mbr_t07',
      courtType: 'Tennis',
      date: '2026-04-18',
      time: '08:00',
      duration: 60,
      partySize: 1,
      status: 'confirmed',
    },
    {
      id: 'court_004',
      memberName: 'Susan Park',
      memberId: 'mbr_d02',
      courtType: 'Pickleball',
      date: '2026-04-18',
      time: '10:00',
      duration: 60,
      partySize: 4,
      status: 'pending',
    },
    {
      id: 'court_005',
      memberName: 'Tom Bradford',
      memberId: 'mbr_d03',
      courtType: 'Tennis',
      date: '2026-04-19',
      time: '06:30',
      duration: 90,
      partySize: 2,
      status: 'confirmed',
    },
    {
      id: 'court_006',
      memberName: 'Sandra Chen',
      memberId: 'mbr_t06',
      courtType: 'Pickleball',
      date: '2026-04-20',
      time: '11:00',
      duration: 60,
      partySize: 2,
      status: 'cancelled',
    },
  ];
}

export function getFBOrders() {
  return [
    {
      id: 'fb_001',
      memberName: 'Anne Jordan',
      memberId: 'mbr_t04',
      items: 'Grilled Chicken Wrap, Sweet Potato Fries, Lemonade',
      pickupTime: '12:15',
      status: 'new',
      placedAt: '2026-04-16T11:47:00Z',
    },
    {
      id: 'fb_002',
      memberName: 'James Whitfield',
      memberId: 'mbr_t01',
      items: 'Club Burger, House Salad, Iced Tea',
      pickupTime: '12:30',
      status: 'preparing',
      placedAt: '2026-04-16T11:52:00Z',
    },
    {
      id: 'fb_003',
      memberName: 'Tom Bradford',
      memberId: 'mbr_d03',
      items: 'Caesar Salad, Sparkling Water',
      pickupTime: '12:00',
      status: 'ready',
      placedAt: '2026-04-16T11:30:00Z',
    },
    {
      id: 'fb_004',
      memberName: 'Susan Park',
      memberId: 'mbr_d02',
      items: 'Fish Tacos (x2), Chips and Guac, Arnold Palmer',
      pickupTime: '13:00',
      status: 'new',
      placedAt: '2026-04-16T12:05:00Z',
    },
    {
      id: 'fb_005',
      memberName: 'David Miller',
      memberId: 'mbr_d01',
      items: 'Turkey Sandwich, Cup of Soup, Coffee',
      pickupTime: '11:45',
      status: 'picked_up',
      placedAt: '2026-04-16T11:10:00Z',
    },
  ];
}

export function getCheckinLog() {
  return [
    {
      memberId: 'mbr_d02',
      memberName: 'Susan Park',
      clubId: 'club_demo',
      lat: 33.8721,
      lng: -84.3046,
      timestamp: '2026-04-16T09:07:00Z',
      teetime: '2026-04-16T09:30:00Z',
      autoCheckedIn: true,
      notifiedAt: '2026-04-16T09:07:22Z',
    },
    {
      memberId: 'mbr_d01',
      memberName: 'David Miller',
      clubId: 'club_demo',
      lat: 33.8718,
      lng: -84.3051,
      timestamp: '2026-04-15T07:55:00Z',
      teetime: null,
      autoCheckedIn: true,
      notifiedAt: '2026-04-15T07:55:44Z',
    },
    {
      memberId: 'mbr_t01',
      memberName: 'James Whitfield',
      clubId: 'club_demo',
      lat: 33.8725,
      lng: -84.3038,
      timestamp: '2026-04-14T06:48:00Z',
      teetime: '2026-04-14T07:00:00Z',
      autoCheckedIn: true,
      notifiedAt: '2026-04-14T06:48:10Z',
    },
  ];
}
