/**
 * pinetree-concierge.spec.js
 *
 * Full interactive E2E test suite for Pinetree Country Club.
 * Prerequisites:
 *   1. Run `npm run test:pinetree:setup` first to create the club and import all data.
 *   2. Creds are read from critiques/pinetree-creds.json (generated by setup script).
 *
 * Run:
 *   npm run test:pinetree
 *   (or) APP_URL=https://... npx playwright test tests/e2e/pinetree-concierge.spec.js --reporter=html
 *
 * What this tests:
 *   Suite 1 — Bootstrap: load creds, verify API reachable
 *   Suite 2 — Gate check: all data domains open, pages render with real data
 *   Suite 3 — Agent inbox: sweep ran, at least 1 pending action
 *   Suite 4 — SMS Concierge loop: 8 messages, each triggers expected tool call
 *   Suite 5 — Operations Center: all 5 tabs render correctly
 *   Suite 6 — Approve/Dismiss agent actions end-to-end
 *   Suite 7 — UX screenshot audit across all key pages
 */
import { test, expect, request as pwRequest } from '@playwright/test';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const APP_URL = process.env.APP_URL || 'https://swoop-member-portal-dev.vercel.app';
const RUN_DATE = new Date().toISOString().slice(0, 10);
const CREDS_PATH = path.join(__dirname, '../../..', 'critiques', 'pinetree-creds.json');
const SCREENSHOT_DIR = path.join(__dirname, `screenshots/pinetree-${RUN_DATE}`);

if (!existsSync(SCREENSHOT_DIR)) mkdirSync(SCREENSHOT_DIR, { recursive: true });

// ─── Issue log ────────────────────────────────────────────────────────────────

const issues = [];
let issueCounter = 0;

function addIssue({ severity = 'medium', suite, description, screenshot = null, expected, actual }) {
  issueCounter++;
  const id = `PT-${String(issueCounter).padStart(3, '0')}`;
  issues.push({ id, severity, suite, description, screenshot, expected, actual });
  console.warn(`[${id}] ${severity.toUpperCase()} — ${description}`);
}

async function shot(page, name) {
  const file = path.join(SCREENSHOT_DIR, `${name}.png`);
  try { await page.screenshot({ path: file, fullPage: true }); return file; }
  catch { return null; }
}

function writeReport(clubId) {
  const report = {
    run_date: RUN_DATE, club_id: clubId || 'unknown', issues,
    summary: {
      total_issues: issues.length,
      high: issues.filter(i => i.severity === 'high').length,
      medium: issues.filter(i => i.severity === 'medium').length,
      low: issues.filter(i => i.severity === 'low').length,
    },
  };
  const reportPath = path.join(__dirname, 'reports/pinetree-report.json');
  mkdirSync(path.dirname(reportPath), { recursive: true });
  writeFileSync(reportPath, JSON.stringify(report, null, 2));
  console.log(`\n[report] ${reportPath}`);
  console.log(`[report] ${report.summary.total_issues} issues (${report.summary.high} high, ${report.summary.medium} medium, ${report.summary.low} low)`);
  return report;
}

// ─── API helpers ──────────────────────────────────────────────────────────────

async function postJson(ctx, url, body, headers = {}) {
  const res = await ctx.post(url, {
    data: body,
    headers: { 'Content-Type': 'application/json', ...headers },
    failOnStatusCode: false,
  });
  const text = await res.text();
  let json = null;
  try { json = JSON.parse(text); } catch {}
  return { status: res.status(), json, text };
}

async function getJson(ctx, url, headers = {}) {
  const res = await ctx.get(url, { headers, failOnStatusCode: false });
  const text = await res.text();
  let json = null;
  try { json = JSON.parse(text); } catch {}
  return { status: res.status(), json, text };
}

async function injectAuth(page, token, user, clubId) {
  await page.addInitScript(({ token, user, clubId }) => {
    localStorage.setItem('swoop_auth_token', token);
    localStorage.setItem('swoop_auth_user', JSON.stringify(user));
    localStorage.setItem('swoop_club_id', clubId);
    localStorage.removeItem('swoop_gates');
  }, { token, user, clubId });
  try {
    await page.evaluate(({ token, user, clubId }) => {
      localStorage.setItem('swoop_auth_token', token);
      localStorage.setItem('swoop_auth_user', JSON.stringify(user));
      localStorage.setItem('swoop_club_id', clubId);
    }, { token, user, clubId });
  } catch {}
}

async function poll(fn, { timeout = 30000, interval = 2000 } = {}) {
  const deadline = Date.now() + timeout;
  while (Date.now() < deadline) {
    const result = await fn();
    if (result) return result;
    await new Promise(r => setTimeout(r, interval));
  }
  return null;
}

// ─── Shared state ─────────────────────────────────────────────────────────────

let ctx;
let creds;       // { clubId, email, password }
let auth;        // { token, user }
let authHeaders;
let apiReachable = false;

// ═══════════════════════════════════════════════════════════════════════════
test.describe('Pinetree Country Club E2E', () => {
  test.describe.configure({ mode: 'serial' });

// ═══════════════════════════════════════════════════════════════════════════
// Suite 1 — Bootstrap
// ═══════════════════════════════════════════════════════════════════════════

test.describe('Suite 1 — Bootstrap', () => {
  test.beforeAll(async () => {
    ctx = await pwRequest.newContext({ baseURL: APP_URL });
    let probe;
    try { probe = await getJson(ctx, '/api/auth'); }
    catch (err) { probe = { status: 0, json: null }; }
    apiReachable = probe.status === 401 && probe.json && typeof probe.json.error === 'string';
    if (!apiReachable) {
      console.warn(`[pinetree] APP_URL=${APP_URL} does not serve /api/* — set APP_URL to a Vercel preview URL`);
    }
  });

  test('1.1 — API is reachable', async () => {
    test.skip(!apiReachable, 'APP_URL does not serve /api/*');
    expect(apiReachable).toBe(true);
  });

  test('1.2 — Load Pinetree credentials and get fresh token', async () => {
    test.skip(!apiReachable, 'API not reachable');

    if (!existsSync(CREDS_PATH)) {
      throw new Error(
        `Pinetree creds not found at ${CREDS_PATH}.\n` +
        `Run setup first: APP_URL=${APP_URL} npm run test:pinetree:setup`
      );
    }

    creds = JSON.parse(readFileSync(CREDS_PATH, 'utf8'));
    console.log(`[bootstrap] club: ${creds.clubId}`);

    const r = await postJson(ctx, '/api/auth', { email: creds.email, password: creds.password });
    if (r.status !== 200 || !r.json?.token) {
      throw new Error(`login failed (${r.status}): ${r.text?.slice(0, 200)}`);
    }
    auth = { token: r.json.token, user: r.json.user };
    authHeaders = { Authorization: `Bearer ${auth.token}` };

    expect(creds.clubId).toBeTruthy();
    expect(auth.token).toBeTruthy();
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// Suite 2 — Full Gate Check
// ═══════════════════════════════════════════════════════════════════════════

test.describe('Suite 2 — Full Gate Check', () => {
  test('2.1 — All data gates are open', async () => {
    test.skip(!apiReachable || !creds, 'Skipping');

    const r = await getJson(ctx, '/api/gates', authHeaders);
    expect(r.status).toBe(200);

    const gates = r.json ?? {};
    console.log('[gates]', JSON.stringify(gates));

    for (const gate of ['members', 'tee-sheet', 'fb']) {
      if (!gates[gate]) {
        addIssue({
          severity: 'high', suite: 'Suite 2',
          description: `Gate "${gate}" is not open after full import`,
          expected: 'true', actual: String(gates[gate]),
        });
      }
    }
    expect(gates.members).toBe(true);
  });

  test('2.2 — Member roster has at least 300 members', async () => {
    test.skip(!apiReachable || !creds, 'Skipping');

    const r = await getJson(ctx, '/api/members', authHeaders);
    const count = r.json?.memberRoster?.length ?? r.json?.members?.length ?? r.json?.total ?? 0;
    console.log(`[members] count=${count}`);
    if (count < 100) {
      addIssue({ severity: 'high', suite: 'Suite 2', description: `Only ${count} members after import (expected 300+)`, expected: '300+', actual: String(count) });
    }
    expect(count).toBeGreaterThan(0);
  });

  test('2.3 — Members page shows health tier labels', async ({ page }) => {
    test.skip(!apiReachable || !creds, 'Skipping');

    await injectAuth(page, auth.token, auth.user, creds.clubId);
    await page.goto(`${APP_URL}/#/members`);
    await page.waitForTimeout(4000);

    const s = await shot(page, '2-3-members');
    const text = await page.evaluate(() => document.body.innerText);
    const hasHealthData = /HEALTHY|AT RISK|WATCH|CRITICAL|Health Score|health/i.test(text);
    if (!hasHealthData) {
      addIssue({ severity: 'medium', suite: 'Suite 2', description: 'Members page has no health tier data', screenshot: s, expected: 'Health tiers visible', actual: text.slice(0, 300) });
    }
  });

  test('2.4 — Today view is populated (not empty state)', async ({ page }) => {
    test.skip(!apiReachable || !creds, 'Skipping');

    await injectAuth(page, auth.token, auth.user, creds.clubId);
    await page.goto(`${APP_URL}/#/today`);
    await page.waitForTimeout(4000);

    const s = await shot(page, '2-4-today');
    const text = await page.evaluate(() => document.body.innerText);
    if (text.length < 500) {
      addIssue({ severity: 'medium', suite: 'Suite 2', description: 'Today view appears empty', screenshot: s, expected: '> 500 chars', actual: `${text.length} chars` });
    }
  });

  test('2.5 — Revenue page shows F&B data', async ({ page }) => {
    test.skip(!apiReachable || !creds, 'Skipping');

    await injectAuth(page, auth.token, auth.user, creds.clubId);
    await page.goto(`${APP_URL}/#/revenue`);
    await page.waitForTimeout(4000);

    const s = await shot(page, '2-5-revenue');
    const text = await page.evaluate(() => document.body.innerText);
    const isGated = /connect your|no data imported|not yet available/i.test(text);
    if (isGated) {
      addIssue({ severity: 'medium', suite: 'Suite 2', description: 'Revenue page still gated after POS import', screenshot: s, expected: 'Revenue data visible', actual: text.slice(0, 200) });
    }
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// Suite 3 — Agent Inbox Populated
// ═══════════════════════════════════════════════════════════════════════════

test.describe('Suite 3 — Agent Inbox', () => {
  test('3.1 — Agent sweep produces pending actions', async () => {
    test.skip(!apiReachable || !creds, 'Skipping');

    let r = await getJson(ctx, `/api/agents?club_id=${creds.clubId}`, authHeaders);
    let pending = (r.json?.actions || []).filter(a => a.status === 'pending');
    console.log(`[agents] ${pending.length} pending actions on first check`);

    if (pending.length === 0) {
      // Re-trigger sweep and poll up to 30s
      console.log('[agents] Inbox empty — re-triggering sweep...');
      await postJson(ctx, `/api/agent-autonomous?clubId=${creds.clubId}`, {}, authHeaders);

      const result = await poll(async () => {
        const r2 = await getJson(ctx, `/api/agents?club_id=${creds.clubId}`, authHeaders);
        const p = (r2.json?.actions || []).filter(a => a.status === 'pending');
        return p.length > 0 ? p : null;
      }, { timeout: 30000, interval: 3000 });

      pending = result || [];
    }

    if (pending.length === 0) {
      addIssue({ severity: 'medium', suite: 'Suite 3', description: 'No pending agent actions after sweep', expected: '≥ 1 pending action', actual: '0' });
    } else {
      console.log(`[agents] ${pending.length} pending action(s) in inbox`);
    }
  });

  test('3.2 — Automations inbox tab shows pending action cards', async ({ page }) => {
    test.skip(!apiReachable || !creds, 'Skipping');

    await injectAuth(page, auth.token, auth.user, creds.clubId);
    await page.goto(`${APP_URL}/#/automations`);
    await page.waitForTimeout(3500);

    const s = await shot(page, '3-2-automations-inbox');
    const text = await page.evaluate(() => document.body.innerText);
    const hasInboxContent = /approve|dismiss|pending|autopilot|No pending/i.test(text);
    if (!hasInboxContent) {
      addIssue({ severity: 'medium', suite: 'Suite 3', description: 'Automations inbox has no content', screenshot: s, expected: 'Pending action cards or empty state', actual: text.slice(0, 300) });
    }
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// Suite 4 — SMS Concierge Interaction Loop
// ═══════════════════════════════════════════════════════════════════════════

test.describe('Suite 4 — SMS Concierge Tool Calls', () => {
  // 8 conversations, each expecting a specific tool to appear in the right panel
  const CONVERSATIONS = [
    { msg: 'Book my usual Saturday 7 AM tee time with 3 friends',   tool: 'book_tee_time',           label: '⛳ book_tee_time' },
    { msg: "What's on the club calendar this weekend?",              tool: 'get_club_calendar',        label: '📅 get_club_calendar' },
    { msg: 'Show me my upcoming schedule and reservations',          tool: 'get_my_schedule',          label: '🗓 get_my_schedule' },
    { msg: 'Book dinner for Saturday at 7pm for 2 people',           tool: 'make_dining_reservation',  label: '🍽 make_dining_reservation' },
    { msg: 'RSVP me for the spring wine dinner',                     tool: 'rsvp_event',               label: '✅ rsvp_event' },
    { msg: 'My lunch yesterday took 45 minutes and no one checked on us', tool: 'file_complaint',     label: '📝 file_complaint' },
    { msg: 'Cancel my upcoming tee time please',                     tool: 'cancel_tee_time',          label: '❌ cancel_tee_time' },
    { msg: 'Can you let the pro shop know I need rental clubs Sunday', tool: 'send_request_to_club',   label: '📨 send_request_to_club' },
  ];

  for (const { msg, tool, label } of CONVERSATIONS) {
    test(`4 — [${label}] "${msg.slice(0, 50)}..."`, async ({ page }) => {
      test.skip(!apiReachable || !creds, 'Skipping');

      await injectAuth(page, auth.token, auth.user, creds.clubId);
      // Navigate to Operations Center, SMS tab
      await page.goto(`${APP_URL}/#/operations`);
      await page.waitForTimeout(2500);

      // Click SMS tab
      const smsTab = page.locator('button[role="tab"]:has-text("SMS"), button:has-text("SMS")').first();
      if (await smsTab.isVisible({ timeout: 4000 })) {
        await smsTab.click();
        await page.waitForTimeout(1500);
      }

      // Make sure James Whitfield is selected (first persona)
      const jamesCard = page.locator('button:has-text("James")').first();
      if (await jamesCard.isVisible({ timeout: 3000 })) {
        await jamesCard.click();
        await page.waitForTimeout(500);
      }

      // Find message input — SMS simulator chat input
      const input = page.locator('input[placeholder*="Message"]').first();
      if (!await input.isVisible({ timeout: 5000 })) {
        addIssue({ severity: 'high', suite: 'Suite 4', description: `Message input not found for tool: ${tool}`, expected: 'Input visible', actual: 'Not found' });
        return;
      }

      await input.fill(msg);
      await input.press('Enter');

      // Wait for agent response (up to 15s)
      await page.waitForFunction(() => {
        const bubbles = document.querySelectorAll('[class*="rounded-2xl"]');
        // Look for an assistant bubble that appeared after our message
        return bubbles.length >= 2;
      }, { timeout: 15000 }).catch(() => {});

      await page.waitForTimeout(2000);

      // Click Tool Calls tab to inspect
      const toolsTab = page.locator('button:has-text("Tool Calls")').first();
      if (await toolsTab.isVisible({ timeout: 3000 })) {
        await toolsTab.click();
        await page.waitForTimeout(800);
      }

      const s = await shot(page, `4-${tool}`);
      const text = await page.evaluate(() => document.body.innerText);
      const toolVisible = text.toLowerCase().includes(tool.replace(/_/g, '_'));

      if (!toolVisible) {
        addIssue({
          severity: 'medium', suite: 'Suite 4',
          description: `Expected tool "${tool}" not visible in tool call panel after message`,
          screenshot: s,
          expected: `${tool} in right panel`,
          actual: `Tool calls panel text: ${text.slice(0, 200)}`,
        });
      } else {
        console.log(`[suite4] ${label} — tool call confirmed in panel`);
      }
    });
  }
});

// ═══════════════════════════════════════════════════════════════════════════
// Suite 5 — Operations Center Navigation
// ═══════════════════════════════════════════════════════════════════════════

test.describe('Suite 5 — Operations Center', () => {
  test('5.1 — Activity tab renders log items', async ({ page }) => {
    test.skip(!apiReachable || !creds, 'Skipping');

    await injectAuth(page, auth.token, auth.user, creds.clubId);
    await page.goto(`${APP_URL}/#/operations`);
    await page.waitForTimeout(3000);

    const s = await shot(page, '5-1-operations-activity');
    const text = await page.evaluate(() => document.body.innerText);
    // Activity log should have some entries (from the mock service)
    const hasActivity = /agent action|member alert|concierge|court|f&b|checkin|booking/i.test(text);
    if (!hasActivity) {
      addIssue({ severity: 'medium', suite: 'Suite 5', description: 'Operations Activity tab shows no log items', screenshot: s, expected: 'Activity items visible', actual: text.slice(0, 300) });
    }
  });

  test('5.2 — Court Bookings tab renders', async ({ page }) => {
    test.skip(!apiReachable || !creds, 'Skipping');

    await injectAuth(page, auth.token, auth.user, creds.clubId);
    await page.goto(`${APP_URL}/#/operations`);
    await page.waitForTimeout(2500);

    const courtsTab = page.locator('button:has-text("Court Bookings"), button:has-text("Courts")').first();
    if (await courtsTab.isVisible({ timeout: 4000 })) {
      await courtsTab.click();
      await page.waitForTimeout(2000);
    }
    const s = await shot(page, '5-2-operations-courts');
    const text = await page.evaluate(() => document.body.innerText);
    const hasCourts = /tennis|pickleball|court|reservation/i.test(text);
    if (!hasCourts) {
      addIssue({ severity: 'medium', suite: 'Suite 5', description: 'Court Bookings tab has no content', screenshot: s, expected: 'Court reservation rows visible', actual: text.slice(0, 200) });
    }
  });

  test('5.3 — F&B Orders tab renders', async ({ page }) => {
    test.skip(!apiReachable || !creds, 'Skipping');

    await injectAuth(page, auth.token, auth.user, creds.clubId);
    await page.goto(`${APP_URL}/#/operations`);
    await page.waitForTimeout(2500);

    const fbTab = page.locator('button:has-text("F&B Orders"), button:has-text("F&B")').first();
    if (await fbTab.isVisible({ timeout: 4000 })) {
      await fbTab.click();
      await page.waitForTimeout(2000);
    }
    const s = await shot(page, '5-3-operations-fb');
    const text = await page.evaluate(() => document.body.innerText);
    const hasFB = /order|pickup|preparing|ready|new|picked up/i.test(text);
    if (!hasFB) {
      addIssue({ severity: 'medium', suite: 'Suite 5', description: 'F&B Orders tab has no content', screenshot: s, expected: 'Order queue items visible', actual: text.slice(0, 200) });
    }
  });

  test('5.4 — Voice tab renders mic button', async ({ page }) => {
    test.skip(!apiReachable || !creds, 'Skipping');

    await injectAuth(page, auth.token, auth.user, creds.clubId);
    await page.goto(`${APP_URL}/#/operations`);
    await page.waitForTimeout(2500);

    const voiceTab = page.locator('button:has-text("Voice")').first();
    if (await voiceTab.isVisible({ timeout: 4000 })) {
      await voiceTab.click();
      await page.waitForTimeout(2000);
    }
    const s = await shot(page, '5-4-operations-voice');
    const text = await page.evaluate(() => document.body.innerText);
    // Should show either the mic button or the API key warning
    const hasVoiceUI = /voice concierge|tap to start|gemini|api key|mic/i.test(text);
    if (!hasVoiceUI) {
      addIssue({ severity: 'medium', suite: 'Suite 5', description: 'Voice tab has no voice UI', screenshot: s, expected: 'Mic button or API key warning visible', actual: text.slice(0, 200) });
    }
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// Suite 6 — Approve / Dismiss Agent Actions
// ═══════════════════════════════════════════════════════════════════════════

test.describe('Suite 6 — Approve & Dismiss Actions', () => {
  test('6.1 — Approve an agent action via SMS Simulator Agent Inbox', async ({ page }) => {
    test.skip(!apiReachable || !creds, 'Skipping');

    // Verify there's a pending action via API first
    const r = await getJson(ctx, `/api/agents?club_id=${creds.clubId}`, authHeaders);
    const pending = (r.json?.actions || []).filter(a => a.status === 'pending');
    if (pending.length === 0) {
      console.log('[suite6] No pending actions — skipping approve test');
      return;
    }
    const initialCount = pending.length;

    await injectAuth(page, auth.token, auth.user, creds.clubId);
    await page.goto(`${APP_URL}/#/operations`);
    await page.waitForTimeout(2500);

    // Click SMS tab
    const smsTab = page.locator('button[role="tab"]:has-text("SMS"), button:has-text("SMS")').first();
    if (await smsTab.isVisible({ timeout: 4000 })) {
      await smsTab.click();
      await page.waitForTimeout(1500);
    }

    // Click Agent Inbox sub-tab in right panel
    const inboxTab = page.locator('button:has-text("Agent Inbox")').first();
    if (!await inboxTab.isVisible({ timeout: 5000 })) {
      addIssue({ severity: 'high', suite: 'Suite 6', description: 'Agent Inbox tab not found in SMS Simulator', expected: 'Tab visible', actual: 'Not found' });
      return;
    }
    await inboxTab.click();
    await page.waitForTimeout(2000);

    const approveBtn = page.locator('button:has-text("Approve")').first();
    if (!await approveBtn.isVisible({ timeout: 5000 })) {
      console.log('[suite6] No Approve button visible in UI');
      return;
    }

    await approveBtn.click();
    await page.waitForTimeout(2500);

    const s = await shot(page, '6-1-after-approve');

    // Verify count decreased via API
    const r2 = await getJson(ctx, `/api/agents?club_id=${creds.clubId}`, authHeaders);
    const pendingAfter = (r2.json?.actions || []).filter(a => a.status === 'pending');
    if (pendingAfter.length >= initialCount) {
      addIssue({ severity: 'medium', suite: 'Suite 6', description: 'Approving action did not reduce pending count', screenshot: s, expected: `< ${initialCount}`, actual: String(pendingAfter.length) });
    } else {
      console.log(`[suite6] Approve OK: ${initialCount} → ${pendingAfter.length} pending`);
    }
  });

  test('6.2 — Dismiss an agent action via SMS Simulator Agent Inbox', async ({ page }) => {
    test.skip(!apiReachable || !creds, 'Skipping');

    const r = await getJson(ctx, `/api/agents?club_id=${creds.clubId}`, authHeaders);
    const pending = (r.json?.actions || []).filter(a => a.status === 'pending');
    if (pending.length < 1) {
      console.log('[suite6] No pending actions for dismiss test — skipping');
      return;
    }
    const initialCount = pending.length;

    await injectAuth(page, auth.token, auth.user, creds.clubId);
    await page.goto(`${APP_URL}/#/operations`);
    await page.waitForTimeout(2500);

    const smsTab = page.locator('button[role="tab"]:has-text("SMS"), button:has-text("SMS")').first();
    if (await smsTab.isVisible({ timeout: 4000 })) { await smsTab.click(); await page.waitForTimeout(1500); }

    const inboxTab = page.locator('button:has-text("Agent Inbox")').first();
    if (!await inboxTab.isVisible({ timeout: 5000 })) return;
    await inboxTab.click();
    await page.waitForTimeout(2000);

    const dismissBtn = page.locator('button:has-text("Dismiss")').first();
    if (!await dismissBtn.isVisible({ timeout: 5000 })) { console.log('[suite6] No Dismiss button visible'); return; }

    await dismissBtn.click();
    await page.waitForTimeout(2500);

    // Confirm dismiss dialog if it appears
    const confirmBtn = page.locator('button:has-text("Confirm dismiss")').first();
    if (await confirmBtn.isVisible({ timeout: 2000 })) {
      await confirmBtn.click();
      await page.waitForTimeout(2000);
    }

    const s = await shot(page, '6-2-after-dismiss');
    const r2 = await getJson(ctx, `/api/agents?club_id=${creds.clubId}`, authHeaders);
    const pendingAfter = (r2.json?.actions || []).filter(a => a.status === 'pending');
    if (pendingAfter.length >= initialCount) {
      addIssue({ severity: 'medium', suite: 'Suite 6', description: 'Dismissing action did not reduce pending count', screenshot: s, expected: `< ${initialCount}`, actual: String(pendingAfter.length) });
    } else {
      console.log(`[suite6] Dismiss OK: ${initialCount} → ${pendingAfter.length} pending`);
    }
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// Suite 7 — UX Screenshot Audit
// ═══════════════════════════════════════════════════════════════════════════

test.describe('Suite 7 — UX Screenshot Audit', () => {
  const PAGES = [
    { route: 'today',        name: '7-today' },
    { route: 'members',      name: '7-members' },
    { route: 'revenue',      name: '7-revenue' },
    { route: 'tee-sheet',    name: '7-tee-sheet' },
    { route: 'automations',  name: '7-automations' },
    { route: 'operations',   name: '7-operations' },
    { route: 'board-report', name: '7-board-report' },
    { route: 'service',      name: '7-service' },
  ];

  for (const { route, name } of PAGES) {
    test(`7 — #/${route}`, async ({ page }) => {
      test.skip(!apiReachable || !creds, 'Skipping');

      await injectAuth(page, auth.token, auth.user, creds.clubId);
      await page.goto(`${APP_URL}/#/${route}`);
      await page.waitForTimeout(3500);

      const s = await shot(page, name);
      const text = await page.evaluate(() => document.body.innerText);
      const hasErrors = /something went wrong|uncaught|error boundary|failed to fetch/i.test(text);

      if (hasErrors) {
        addIssue({ severity: 'high', suite: 'Suite 7', description: `Error state on #/${route}`, screenshot: s, expected: 'No errors', actual: text.slice(0, 200) });
      }
      if (text.length < 200) {
        addIssue({ severity: 'medium', suite: 'Suite 7', description: `#/${route} appears blank (${text.length} chars)`, screenshot: s, expected: '> 200 chars', actual: `${text.length} chars` });
      }

      console.log(`[audit] #/${route}: ${text.length} chars, errors=${hasErrors}`);
    });
  }
});

// ═══════════════════════════════════════════════════════════════════════════

test.afterAll(async () => {
  if (ctx) await ctx.dispose();
  writeReport(creds?.clubId);
});

}); // end outer describe 'Pinetree Country Club E2E'
