import { theme } from '@/config/theme';

// config/navigation.js — decision-based GM navigation items
// Each entry declares sourceSystems for data provenance display
export const navItems = [
  {
    key: 'daily-briefing',
    label: 'Daily Briefing',
    icon: '📋',
    color: theme.colors.navBriefing,
    subtitle: 'What needs my attention today?',
    sourceSystems: ['Tee Sheet', 'POS', 'Member CRM', 'Scheduling'],
  },
  {
    key: 'operations',
    label: 'Operations',
    icon: '⌘',
    color: theme.colors.navOperations,
    subtitle: 'How is the golf operation running?',
    sourceSystems: ['Tee Sheet', 'Weather API'],
  },
  {
    key: 'waitlist-demand',
    label: 'Tee Sheet & Demand',
    icon: '⟳',
    color: theme.colors.navWaitlist,
    subtitle: 'Who is waiting, who will cancel, and what does it cost?',
    sourceSystems: ['Tee Sheet', 'Member CRM', 'POS', 'Weather API'],
  },
  {
    key: 'location-intelligence',
    label: 'Location Intelligence',
    icon: '📍',
    color: theme.colors.navOperations,
    subtitle: 'Where is everyone on property right now?',
    sourceSystems: ['Swoop App', 'Member CRM'],
    hidden: true,
  },
  {
    key: 'fb-performance',
    label: 'F&B Operations',
    icon: '◆',
    color: theme.colors.navFb,
    subtitle: 'Where is money being made or lost?',
    sourceSystems: ['POS', 'Tee Sheet', 'Weather API'],
  },
  {
    key: 'member-health',
    label: 'Member Intelligence',
    icon: '◉',
    color: theme.colors.navMembers,
    subtitle: 'Who is at risk and what do we do?',
    sourceSystems: ['Member CRM', 'Analytics', 'Tee Sheet'],
  },
  {
    key: 'staffing-service',
    label: 'Staffing & Labor',
    icon: '⊞',
    color: theme.colors.navStaffing,
    subtitle: 'Are we staffed right and serving members well?',
    sourceSystems: ['Scheduling', 'POS', 'Member CRM'],
  },
  {
    key: 'growth-pipeline',
    label: 'Revenue & Pipeline',
    icon: '◎',
    color: theme.colors.navPipeline,
    subtitle: 'Which guests are ready to become members?',
    sourceSystems: ['Tee Sheet', 'Analytics'],
  },
  {
    key: 'agent-command',
    label: 'Recommended Actions',
    icon: '⬡',
    color: theme.colors.navAgents,
    subtitle: 'Approve or assign high-impact actions before members feel the pain.',
    sourceSystems: ['All Systems'],
  },
  {
    key: 'integrations',
    label: 'Integrations',
    icon: '🔌',
    color: theme.colors.navIntegrations,
    subtitle: 'Connect your systems. Unlock intelligence.',
    sourceSystems: [],
  },
  {
    key: 'integrations/csv-import',
    label: 'CSV Import Hub',
    icon: '⬇️',
    color: theme.colors.navIntegrations,
    subtitle: 'Upload CSV/XLSX when APIs are missing.',
    sourceSystems: [],
  },
  {
    key: 'demo-mode',
    label: 'Demo Mode',
    icon: '▶',
    color: theme.colors.navDemo,
    subtitle: 'Guided walkthroughs for demos',
    sourceSystems: [],
    hidden: true, // Accessible via /#/demo-mode URL only — not shown in main nav
  },
];
export const NAV_ITEMS = navItems;
