/**
 * Explainability API
 * GET /api/tools/explain?club_id=...&action_id=...
 *
 * Builds a full causal chain for an agent-recommended action by joining
 * member health scores, activity, complaints, membership details, and
 * historical intervention outcomes.
 */
import { sql } from '@vercel/postgres';
import { withAuth, getReadClubId } from '../lib/withAuth.js';

/**
 * Build a human-readable explanation paragraph from the causal chain.
 */
function buildExplanationText({ action, member, causalChain, similarInterventions }) {
  const memberName = member?.name || 'This member';
  const headline = action?.headline || 'this action';
  const signals = causalChain.map(c => c.signal).join(', ');
  const successRate = similarInterventions.total > 0
    ? `${Math.round(similarInterventions.success_rate * 100)}%`
    : 'unknown';

  return (
    `${memberName} was flagged for "${headline}" based on the following signals: ${signals || 'general risk indicators'}. ` +
    `Their current health score is ${member?.health_score ?? 'unavailable'}, ` +
    `with annual dues of $${member?.annual_dues?.toLocaleString() ?? 'N/A'} ` +
    `and a renewal date of ${member?.renewal_date || 'unknown'}. ` +
    `Based on ${similarInterventions.total} similar past interventions, ` +
    `the expected success rate is ${successRate}. ` +
    `This recommendation was generated by the ${action?.agent_id || 'agent'} agent.`
  );
}

export default withAuth(async function handler(req, res) {
  if (req.method !== 'GET') return res.status(405).json({ error: 'GET only' });

  const clubId = getReadClubId(req);
  const actionId = req.query.action_id;

  if (!actionId) {
    return res.status(400).json({ error: 'action_id query parameter is required' });
  }

  try {
    // ── 1. Fetch the action ────────────────────────────────────────
    const actionResult = await sql`
      SELECT * FROM agent_actions
      WHERE club_id = ${clubId} AND id = ${actionId}
    `;
    const action = actionResult.rows[0];
    if (!action) {
      return res.status(404).json({ error: 'Action not found' });
    }

    const memberId = action.member_id;
    const causalChain = [];

    // ── 2. Member health score ─────────────────────────────────────
    let memberHealth = null;
    try {
      const hsResult = await sql`
        SELECT member_id, health_score, churn_risk, engagement_score, updated_at
        FROM health_scores
        WHERE club_id = ${clubId} AND member_id = ${memberId}
        ORDER BY updated_at DESC
        LIMIT 1
      `;
      memberHealth = hsResult.rows[0] || null;
      if (memberHealth) {
        causalChain.push({
          signal: 'Health score decline',
          source: 'health_scores',
          detail: `Current score: ${memberHealth.health_score}, churn risk: ${memberHealth.churn_risk}, engagement: ${memberHealth.engagement_score}`,
          timestamp: memberHealth.updated_at?.toISOString() || null,
        });
      }
    } catch { /* table may not exist yet */ }

    // ── 3. Member activity (golf, dining, events) ──────────────────
    let activityRows = [];
    try {
      const actResult = await sql`
        SELECT activity_type, activity_date, details
        FROM member_activity
        WHERE club_id = ${clubId} AND member_id = ${memberId}
        ORDER BY activity_date DESC
        LIMIT 10
      `;
      activityRows = actResult.rows;

      const typeCounts = {};
      for (const row of activityRows) {
        typeCounts[row.activity_type] = (typeCounts[row.activity_type] || 0) + 1;
      }

      if (activityRows.length > 0) {
        const lastActivity = activityRows[0];
        causalChain.push({
          signal: 'Activity pattern',
          source: 'member_activity',
          detail: `Last activity: ${lastActivity.activity_type} on ${lastActivity.activity_date}. Recent breakdown: ${JSON.stringify(typeCounts)}`,
          timestamp: lastActivity.activity_date?.toISOString?.() || String(lastActivity.activity_date),
        });
      } else {
        causalChain.push({
          signal: 'No recent activity',
          source: 'member_activity',
          detail: 'No activity records found for this member',
          timestamp: null,
        });
      }
    } catch { /* table may not exist yet */ }

    // ── 4. Complaints ──────────────────────────────────────────────
    let complaints = [];
    try {
      const compResult = await sql`
        SELECT id, status, category, created_at
        FROM complaints
        WHERE club_id = ${clubId} AND member_id = ${memberId}
        ORDER BY created_at DESC
        LIMIT 5
      `;
      complaints = compResult.rows;

      const openComplaints = complaints.filter(c => c.status === 'open' || c.status === 'pending');
      if (openComplaints.length > 0) {
        causalChain.push({
          signal: 'Open complaints',
          source: 'complaints',
          detail: `${openComplaints.length} open complaint(s). Categories: ${openComplaints.map(c => c.category).join(', ')}`,
          timestamp: openComplaints[0].created_at?.toISOString() || null,
        });
      } else if (complaints.length > 0) {
        causalChain.push({
          signal: 'Complaint history',
          source: 'complaints',
          detail: `${complaints.length} total complaint(s), all resolved. Last: ${complaints[0].created_at}`,
          timestamp: complaints[0].created_at?.toISOString?.() || String(complaints[0].created_at),
        });
      }
    } catch { /* table may not exist yet */ }

    // ── 5. Membership details ──────────────────────────────────────
    let member = null;
    try {
      const memResult = await sql`
        SELECT member_id, name, membership_type, renewal_date, join_date, annual_dues, status
        FROM members
        WHERE club_id = ${clubId} AND member_id = ${memberId}
      `;
      member = memResult.rows[0] || null;

      if (member) {
        const tenure = member.join_date
          ? Math.floor((Date.now() - new Date(member.join_date).getTime()) / (365.25 * 24 * 60 * 60 * 1000))
          : null;

        causalChain.push({
          signal: 'Membership profile',
          source: 'members',
          detail: `Type: ${member.membership_type}, dues: $${member.annual_dues}, tenure: ${tenure ?? 'unknown'} years, renewal: ${member.renewal_date || 'N/A'}`,
          timestamp: null,
        });
      }
    } catch { /* table may not exist yet */ }

    // ── 6. Historical outcomes (similar interventions) ─────────────
    let similarInterventions = { total: 0, success_rate: 0 };
    try {
      const outResult = await sql`
        SELECT COUNT(*) AS total,
               COUNT(*) FILTER (WHERE outcome = 'success') AS successes
        FROM intervention_outcomes
        WHERE club_id = ${clubId}
          AND action_type = ${action.action_type || action.type || 'unknown'}
      `;
      const row = outResult.rows[0];
      const total = parseInt(row?.total, 10) || 0;
      const successes = parseInt(row?.successes, 10) || 0;
      similarInterventions = {
        total,
        success_rate: total > 0 ? successes / total : 0,
      };
    } catch { /* table may not exist yet */ }

    // ── 7. Value at risk ───────────────────────────────────────────
    const annualDues = parseFloat(member?.annual_dues) || 0;
    const churnRisk = parseFloat(memberHealth?.churn_risk) || 0.5;
    const valueAtRisk = Math.round(annualDues * churnRisk);

    // ── 8. Confidence score ────────────────────────────────────────
    // Heuristic: more data signals = higher confidence
    let confidence = 0.3; // base
    if (memberHealth) confidence += 0.2;
    if (activityRows.length > 0) confidence += 0.15;
    if (complaints.length > 0) confidence += 0.1;
    if (member) confidence += 0.15;
    if (similarInterventions.total >= 5) confidence += 0.1;
    confidence = Math.min(confidence, 1.0);

    // ── Build response ─────────────────────────────────────────────
    const explanation = {
      action_summary: action.headline || action.summary || `Action ${actionId}`,
      causal_chain: causalChain,
      value_at_risk: valueAtRisk,
      confidence: Math.round(confidence * 100) / 100,
      similar_interventions: similarInterventions,
      recommended_by: action.agent_id || action.recommended_by || 'unknown',
      explanation_text: buildExplanationText({
        action,
        member: { ...member, health_score: memberHealth?.health_score },
        causalChain,
        similarInterventions,
      }),
    };

    return res.status(200).json(explanation);
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});
