import type { VercelRequest, VercelResponse } from '@vercel/node'
import { sql } from '@vercel/postgres'

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'GET') return res.status(405).end()
  const clubId = (req.query.club_id as string) || 'bowling-green-cc'
  const format = (req.query.format as string) || 'html'

  const [reportRow, boardRow] = await Promise.all([
    sql`SELECT * FROM board_reports WHERE club_id = ${clubId} ORDER BY generated_at DESC LIMIT 1`,
    sql`
      SELECT
        (SELECT COUNT(*)::int FROM agent_handoffs WHERE club_id = ${clubId} AND status = 'approved' AND recommendation_type = 'member_save') AS members_saved,
        (SELECT COALESCE(SUM(m.annual_dues), 0)::int FROM agent_handoffs h JOIN members m ON m.member_id = h.member_id WHERE h.club_id = ${clubId} AND h.status = 'approved' AND h.recommendation_type = 'member_save') AS dues_protected,
        (SELECT COUNT(*)::int FROM complaints WHERE club_id = ${clubId} AND status = 'resolved') AS service_interventions,
        (SELECT COUNT(*)::int FROM agent_handoffs WHERE club_id = ${clubId}) AS total_decisions
    `,
  ])

  const report   = reportRow.rows[0] ?? null
  const headline = boardRow.rows[0]
  const month    = report ? report.month : new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })
  const content  = report?.content ?? '(No report generated yet. Click "Generate report" in the Board view.)'

  const fmt = (n: number) =>
    n >= 1_000_000 ? `$${(n / 1_000_000).toFixed(1)}M` : n >= 1_000 ? `$${(n / 1_000).toFixed(0)}K` : `$${n}`

  if (format === 'txt') {
    const text = [
      'ClubThread · Board Intelligence Packet',
      `Bowling Green Country Club · ${month}`,
      '─'.repeat(60),
      '',
      'HEADLINE METRICS',
      `Members saved:          ${headline?.members_saved ?? 0}`,
      `Dues protected:         ${fmt(headline?.dues_protected ?? 0)}`,
      `Service interventions:  ${headline?.service_interventions ?? 0}`,
      `Total GM decisions:     ${headline?.total_decisions ?? 0}`,
      '',
      '─'.repeat(60),
      '',
      'BOARD REPORT DRAFT',
      '',
      content,
      '',
      '─'.repeat(60),
      `Generated by ClubThread on ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`,
    ].join('\n')

    res.setHeader('Content-Type', 'text/plain; charset=utf-8')
    res.setHeader('Content-Disposition', `attachment; filename="board-report-${month.replace(/\s/g, '-').toLowerCase()}.txt"`)
    return res.send(text)
  }

  // HTML — print-optimized; user can Ctrl+P → Save as PDF
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Board Report — ${month}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,500;1,400;1,500&family=Inter:wght@400;500;600&display=swap');
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Inter', sans-serif; color: #1a1f1b; background: #fff; font-size: 12pt; line-height: 1.6; }
  .page { max-width: 760px; margin: 0 auto; padding: 48px 40px; }
  .rule { border: none; border-top: 1px solid rgba(26,31,27,0.15); margin: 24px 0; }
  .rule-dashed { border: none; border-top: 1px dashed rgba(26,31,27,0.12); margin: 20px 0; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 32px; padding-bottom: 24px; border-bottom: 3px solid #3d6a4b; }
  .header-logo { font-family: 'EB Garamond', serif; font-size: 10pt; letter-spacing: 0.2em; text-transform: uppercase; color: rgba(26,31,27,0.45); }
  .header-title { font-family: 'EB Garamond', serif; font-size: 22pt; font-weight: 500; color: #1a1f1b; line-height: 1.2; margin: 4px 0; }
  .header-sub { font-size: 9pt; color: rgba(26,31,27,0.5); }
  .headline-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 0; border: 1px solid rgba(26,31,27,0.12); border-radius: 4px; overflow: hidden; margin-bottom: 32px; }
  .headline-cell { padding: 16px 18px; border-right: 1px solid rgba(26,31,27,0.1); }
  .headline-cell:last-child { border-right: none; }
  .headline-label { font-size: 7.5pt; font-weight: 600; letter-spacing: 0.1em; text-transform: uppercase; color: rgba(26,31,27,0.4); margin-bottom: 6px; }
  .headline-value { font-family: 'EB Garamond', serif; font-size: 24pt; font-weight: 500; color: #1a1f1b; line-height: 1; }
  .section-title { font-family: 'EB Garamond', serif; font-size: 13pt; font-weight: 500; color: #1a1f1b; margin-bottom: 14px; }
  .report-body { font-size: 10.5pt; color: #2d3930; line-height: 1.8; white-space: pre-wrap; padding-left: 16px; border-left: 3px solid rgba(196,165,115,0.7); }
  .footer { font-size: 8pt; color: rgba(26,31,27,0.35); text-align: center; margin-top: 40px; padding-top: 16px; border-top: 1px solid rgba(26,31,27,0.1); }
  .print-note { background: rgba(61,106,75,0.07); border: 1px solid rgba(61,106,75,0.2); border-radius: 4px; padding: 12px 16px; margin-bottom: 24px; font-size: 9.5pt; color: #3d6a4b; }
  @media print {
    .print-note { display: none; }
    body { font-size: 10pt; }
    .page { padding: 20px; }
  }
</style>
</head>
<body>
<div class="page">
  <div class="print-note">
    To save as PDF: File → Print → Destination: Save as PDF (or press Ctrl+P / Cmd+P)
  </div>

  <div class="header">
    <div>
      <div class="header-logo">ClubThread · Board Intelligence</div>
      <div class="header-title">Board Intelligence Packet</div>
      <div class="header-sub">Bowling Green Country Club · ${month}</div>
    </div>
    <div style="text-align:right; font-size:9pt; color:rgba(26,31,27,0.4);">
      Generated ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}<br>
      Confidential — Board use only
    </div>
  </div>

  <div class="headline-grid">
    <div class="headline-cell">
      <div class="headline-label">Members saved</div>
      <div class="headline-value">${headline?.members_saved ?? 0}</div>
    </div>
    <div class="headline-cell">
      <div class="headline-label">Dues protected</div>
      <div class="headline-value">${fmt(headline?.dues_protected ?? 0)}</div>
    </div>
    <div class="headline-cell">
      <div class="headline-label">Service actions</div>
      <div class="headline-value">${headline?.service_interventions ?? 0}</div>
    </div>
    <div class="headline-cell">
      <div class="headline-label">GM decisions</div>
      <div class="headline-value">${headline?.total_decisions ?? 0}</div>
    </div>
  </div>

  <hr class="rule">

  <div class="section-title">Board Report — ${month}</div>
  <div class="report-body">${content.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</div>

  <hr class="rule">

  <div class="footer">
    ClubThread · Bowling Green Country Club · Confidential<br>
    Generated ${new Date().toISOString()}
  </div>
</div>
</body>
</html>`

  res.setHeader('Content-Type', 'text/html; charset=utf-8')
  res.setHeader('Content-Disposition', `inline; filename="board-report-${month.replace(/\s/g, '-').toLowerCase()}.html"`)
  return res.send(html)
}
