/**
 * GET /api/staff-briefs
 *
 * Staff briefs endpoint — returns role-specific or member-specific briefs
 * generated by the Arrival Anticipation Engine.
 *
 * Query params:
 *   ?role=pro_shop&date=2026-04-11   — all briefs for a role on a date
 *   ?member_id=xxx&date=2026-04-11   — all briefs for a member on a date (all roles)
 *
 * Marks briefs as read (sets read_at) when fetched.
 */
import { sql } from '@vercel/postgres';
import { withAuth, getReadClubId } from './lib/withAuth.js';
import { logError } from './lib/logger.js';

async function staffBriefsHandler(req, res) {
  if (req.method !== 'GET') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const clubId = getReadClubId(req);
  const { role, member_id, date } = req.query;

  if (!date) {
    return res.status(400).json({ error: 'date query parameter is required (YYYY-MM-DD)' });
  }

  if (!role && !member_id) {
    return res.status(400).json({ error: 'Either role or member_id query parameter is required' });
  }

  try {
    let briefs;

    if (role) {
      // Fetch briefs for a specific role on a date
      const { rows } = await sql`
        SELECT sb.brief_id, sb.member_id, sb.tee_time, sb.role,
               sb.brief_text, sb.priority, sb.generated_at, sb.read_at,
               m.first_name || ' ' || m.last_name AS member_name
        FROM staff_briefs sb
        JOIN members m ON sb.member_id = m.member_id
        WHERE sb.club_id = ${clubId}
          AND sb.role = ${role}
          AND sb.generated_at::date = ${date}
        ORDER BY sb.tee_time ASC, sb.generated_at ASC
      `;
      briefs = rows;
    } else {
      // Fetch briefs for a specific member on a date (all roles)
      const { rows } = await sql`
        SELECT sb.brief_id, sb.member_id, sb.tee_time, sb.role,
               sb.brief_text, sb.priority, sb.generated_at, sb.read_at,
               m.first_name || ' ' || m.last_name AS member_name
        FROM staff_briefs sb
        JOIN members m ON sb.member_id = m.member_id
        WHERE sb.club_id = ${clubId}
          AND sb.member_id = ${member_id}
          AND sb.generated_at::date = ${date}
        ORDER BY sb.tee_time ASC, sb.role ASC
      `;
      briefs = rows;
    }

    // Mark unread briefs as read
    const unreadIds = briefs
      .filter(b => !b.read_at)
      .map(b => b.brief_id);

    if (unreadIds.length > 0) {
      await sql`
        UPDATE staff_briefs
        SET read_at = NOW()
        WHERE brief_id = ANY(${unreadIds})
      `;
      // Update the response to reflect read status
      const now = new Date().toISOString();
      briefs = briefs.map(b => ({
        ...b,
        read_at: b.read_at || now,
      }));
    }

    return res.status(200).json({
      date,
      filter: role ? { role } : { member_id },
      count: briefs.length,
      briefs,
    });
  } catch (err) {
    logError('/api/staff-briefs', err);
    return res.status(500).json({ error: err.message });
  }
}

export default withAuth(staffBriefsHandler);
